version: '3.2'

networks:
  combined:


services:
  frontend:
    image: con-front-v6
    restart: always
    ports:
      - 80:1000
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=zay_dev
    deploy:
      replicas: 1
    networks:
      - combined

  backend:
    image: con-back-v6
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_DATABASE=zay_dev
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOSTNAME=db
    command: sh -c "npm run db:migrate && npm run db:seed && npm start"
    deploy:
      replicas: 4
    networks:
      - combined

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=zay_dev
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
    networks:
      - combined

volumes:
  db_data:
